# Generated by Django 5.2.4 on 2025-08-10 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_call_callparticipant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="call",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AlterField(
            model_name="call",
            name="call_status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="call_type",
            field=models.CharField(
                choices=[("audio", "Audio"), ("video", "Video")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("emoji", "Emoji"),
                    ("photo", "Photo"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="messagereaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("laugh", "Laugh"),
                    ("wow", "Wow"),
                    ("sad", "Sad"),
                    ("angry", "Angry"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="messagestatusentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="call",
            unique_together={("chat", "initiator", "started_at")},
        ),
    ]
