# Generated by Django 5.2.4 on 2025-08-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_call_options_alter_call_call_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmember",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("admin", "Admin"), ("member", "Member")],
                default="member",
                max_length=20,
                null=True,
            ),
        ),
    ]
