# Generated by Django 5.2.4 on 2025-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagereaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
